### ISSUE TITLE
Issues with some datasets

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/Rdatasets#1]
@kojix2 reported the following: 

---

Hi @vincentarelbundock and Rdatasets developers!

Thank you for creating a very useful repository. 

I found 3 CSV files that have a different name than the `dataset.csv` description.
https://github.com/kojix2/rdatasets/issues/4

* Stat2Data has two identical data sets. `InfantMortality` and `InfantMortality2010`. But it seems only `InfantMortality2010` is described in datasets.csv.
* `Stat2Data/Leafhoppers.csv` is described as `LeafHoppers` in `dataset.csv`
* `survival/genfan.csv` does not exist in `datasets.csv`

Thanks.

**Comment by vincentarelbundock** [comment]
Thanks for the report, @kojix2 ! I hadn't touched Rdatasets in forever, and as I was trying to fix the issues you identified, I quickly realized that the repo was broken beyond repair. I did a complete reboot.

Could you please check if everything works OK now? Some links my have changed, but they should all work. 

Thanks!

**Comment by kojix2** [comment]
Thank you, @vincentarelbundock.
I've confirmed that everything works fine! 
Unfortunately, all the github stars have been lost, though.

I don't have access to the close button. So please feel free to close this issue.

**Comment by vincentarelbundock** [comment]
Well that was pretty dumb of me. The lesson is clear: never commit to github after midnight!

;)

Thanks again!
