### ISSUE TITLE
Request: add state data.

### ISSUE THREAD

**Issue by jseabold** [vincentarelbundock/Rdatasets#13]
Similear to #12. It would have to deal with non-standard data. Perhaps add the datasets separately.

**Comment by PepRoca** [comment]
The package epicalc has been deleted from the r-cran repository (http://cran.r-project.org/web/packages/epicalc/index.html). Could you include data bases of this package. And will be accessible for teaching?

Thanks a lot. Pep

**Comment by vincentarelbundock** [comment]
@PepRoca, I'm sorry but I don't think I'll be adding this one. Two reasons:

1) I'm lazy and this would require the scraping code to consider different versions of a package.
2) I don't want to figure out why packages are withdrawn from CRAN. Perhaps the data should no longer distributed, and I have no way of (and no interest in) verifying myself.

Sorry for the disappointing answer.

**Comment by PepRoca** [comment]
Helo:

Thanks for answering.

Do not worry. I understand your reasoning and surely you are right and it is a bad idea that I proposed.

Best regards. Pep
