### ISSUE TITLE
new dataset: mstate

### ISSUE THREAD

**Issue by alonsosilvaallende** [vincentarelbundock/Rdatasets#14]
https://cran.r-project.org/web/packages/mstate/index.html

**Comment by vincentarelbundock** [comment]
In your opinion, is this data interesting? Would people use it?

**Comment by alonsosilvaallende** [comment]
Yes. Together with my Ph.D student, we are working on survival analysis where most of the datasets are in R (survival, asaur, KMsurv, MASS, mstate, etc.). Now that I found your work I very much appreciate it. Thank you very much.

**Comment by vincentarelbundock** [comment]
thanks! website updated.
