### ISSUE TITLE
starwars dataset only has one row - seems incomplete

### ISSUE THREAD

**Issue by flyaflya** [vincentarelbundock/Rdatasets#15]
Thx for the cool package.

Check this link and you will see that the dataset only has one row. 
  https://vincentarelbundock.github.io/Rdatasets/csv/dplyr/starwars.csv

The original has 87 rows:  https://dplyr.tidyverse.org/reference/starwars.html

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report!

This should now be fixed. But note that I had to drop a couple list columns, because AFAIK there is no clean way to save those as CSV.
