### ISSUE TITLE
Error within O-Rings dataset

### ISSUE THREAD

**Issue by kburchfiel** [vincentarelbundock/Rdatasets#16]
Row 18 of the O-Rings dataset has a "Blowby" value of 2 but a "Total" value of only 1. Since "Total" equals the sum of "Blowby" and "Erosion" values, "Total" in this case should be 2 rather than 1.

**Comment by vincentarelbundock** [comment]
Is the mistake also present in the original package?

I am not responsible for the content of the datasets, only for extracting them from R packages and making them available on this website.
