### ISSUE TITLE
How are updates dealt with?

### ISSUE THREAD

**Issue by saketkc** [vincentarelbundock/Rdatasets#17]
On my local system, running `Rdatasets.R` shows the following files have undergone change:
```
$ git diff
	modified:   csv/KMsurv/rats.csv
	modified:   csv/datasets/sunspot.month.csv
	modified:   csv/survival/mgus.csv
	modified:   csv/survival/rats.csv
	modified:   csv/vcd/Bundesliga.csv
	modified:   datasets.csv
	modified:   datasets.html
<snipped>
```

How are such updates dealt with? The use case being, I was going to request you to add `lme4` datasets. I could have run the script with `lme4` added in the `packages` vector and opened a PR, but then it also generates diff in other files.

**Comment by vincentarelbundock** [comment]
I don't really have a great process: yes, at the moment pretty much all the files get touched in every commit. Not optimal...

Anyway, here you go. I added it for you.

Thanks and sorry for the delay!

**Comment by vincentarelbundock** [comment]
actually, scratch that. the process is not thaaat dumb :)

**Comment by saketkc** [comment]
> actually, scratch that. the process is not thaaat dumb :)

I know! Thanks for hosting this repo, pretty useful :-)
