### ISSUE TITLE
Selection of data sets

### ISSUE THREAD

**Issue by sigbertklinke** [vincentarelbundock/Rdatasets#17]
Hi,
on https://vincentarelbundock.github.io/Rdatasets/articles/data.html you allow to search within the datasets. Would it be possible to select data sets based on conditions, e.g. all data sets with at least two numeric variables and one factor variable?

Best Sigbert

**Comment by vincentarelbundock** [comment]
This is a cool idea, but I do not know how to do this with the `DT` package, which is what I use to create the table.

I would accept a pull request if someone wants to prepare one, but I won't do this myself.

Thanks!
