### ISSUE TITLE
mi and mediation packages

### ISSUE THREAD

**Issue by kshedden** [vincentarelbundock/Rdatasets#18]
Can you add these data sets?

CHAIN and nlsyV from the mi package

shool, boundsdata, framing, CEDdata, jobs from the mediation package

Thanks!

**Comment by vincentarelbundock** [comment]
Probably too late to be of us (sorry!), but I added those two packages: https://github.com/vincentarelbundock/Rdatasets/commit/d0a9091d6cd6255c48e765aa0133a1bfade12b06
