### ISSUE TITLE
Make these datasets available as DataPackage

### ISSUE THREAD

**Issue by scls19fr** [vincentarelbundock/Rdatasets#19]
Hello,

it will be great to make these datasets available as DataPackage
http://data.okfn.org/doc/data-package
http://data.okfn.org/tools

So it will be possible to get these data using Python or R (or any other language where a DataPackage client is available).

see https://github.com/iamaziz/PyDataset/issues/7

Kind regards

**Comment by vincentarelbundock** [comment]
I don't understand why this is relevant. Closing.
