### ISSUE TITLE
Python 3 - memoryview: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by scls19fr** [vincentarelbundock/Rdatasets#21]
Hello,

```
$ python docs2rst.py
```

raises

```
Traceback (most recent call last):
  File "docs2rst.py", line 34, in <module>
    rst = html2rst(open(fin, 'r').read())
  File "docs2rst.py", line 17, in html2rst
    return p.communicate(html)[0]
  File "//anaconda/lib/python3.5/subprocess.py", line 1068, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "//anaconda/lib/python3.5/subprocess.py", line 1687, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'
```

under Python 3

**Comment by scls19fr** [comment]
An other approach might be to use pypandoc

https://github.com/bebraw/pypandoc

**Comment by scls19fr** [comment]
An other idea might be to use R pandoc function from knitr.

See
https://github.com/yihui/knitr/issues/1170
and https://github.com/yihui/knitr/commit/74f629af1177dde594bfb0f88735782cb91525fd

**Comment by vincentarelbundock** [comment]
The rst conversion via python was too much trouble for me, so I removed it. I could accept a pull request but won't work on it myself. Closing this for now.

https://github.com/vincentarelbundock/Rdatasets/commit/772bb40163574226e1db015feae147612ddba2a8
