### ISSUE TITLE
Package suggestion: Add wooldridge package 

### ISSUE THREAD

**Issue by s3alfisc** [vincentarelbundock/Rdatasets#22]
Hi - thanks for organizing this really cool resource! 

I'd like to suggest to add datasets from the `wooldridge` package, which you can find on [CRAN](https://cran.r-project.org/web/packages/wooldridge/index.html). If you'd like, I could also add a PR this or next weekend. 

Best, Alex

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion. The `wooldridge` package datasets are now live on the site.
