### ISSUE TITLE
Add two datasets from `survival` package

### ISSUE THREAD

**Issue by paulduf** [vincentarelbundock/Rdatasets#26]
Hello,

I spotted these two datasets, they are in the R `survival` package, but not in your repository, is there a reason for this, or are you able to add them ?

- `rotterdam` dataset https://rdrr.io/cran/survival/man/rotterdam.html
- `gbsg` dataset https://rdrr.io/cran/survival/man/gbsg.html

Thanks for your work

**Comment by paulduf** [comment]
My bad, I looked at the HTML index ...

**Comment by paulduf** [comment]
Reopening because I don't find them in the `datasets.csv` index

https://github.com/vincentarelbundock/Rdatasets/blob/master/datasets.csv

**Comment by vincentarelbundock** [comment]
I'm not sure how to extract those datasets. They don't seem to be properly exported in the package namespace. If you show me a command that can assign the dataset to a new object, I'll be able to add it. Something like:

```r
packagename <- "survival"
datasetname <- "rotterdam"
x <- [YOUR COMMAND GOES HERE]
```

**Comment by vincentarelbundock** [comment]
I played around with this a bit more and was able to add it.

Thanks for raising the issue.
