### ISSUE TITLE
Datasets from the DAAG package

### ISSUE THREAD

**Issue by jhmaindonald** [vincentarelbundock/Rdatasets#26]
The DAAG package has 127 datasets, albeit a few that bring together historical data are updates of earlier datasets.  You might add these to your list and to your collection.

Note perhaps also small numbers of datasets in the packages gamclass (8 datasets), DAAGbio (5 genomic datasets), and hwde (2 genotype datasets)
[DAAGdata.txt](https://github.com/vincentarelbundock/Rdatasets/files/828893/DAAGdata.txt)

John Maindonald.

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion. DAAG and gamclass added here: https://github.com/vincentarelbundock/Rdatasets/commit/a02a1111b2231c2a0e2b61eb7a34a39dfd2f8bac

For some reason, my script doesn't pick up datasets from DAAGbio. I don't really have time to investigate, unfortunately.
