### ISSUE TITLE
no rst files breaks statsmodels

### ISSUE THREAD

**Issue by josef-pkt** [vincentarelbundock/Rdatasets#27]
removing the rst files in https://github.com/vincentarelbundock/Rdatasets/commit/a02a1111b2231c2a0e2b61eb7a34a39dfd2f8bac
 breaks statsmodels get_rdataset because we use the meta info.

https://github.com/statsmodels/statsmodels/issues/3554

**Comment by vincentarelbundock** [comment]
Huh, that's a big problem. I removed .rst support because the script was broken and didn't think anyone used it.

Will give it a look as soon as I find a minute (soon).

Sorry!

**Comment by vincentarelbundock** [comment]
I think this can be closed https://github.com/vincentarelbundock/Rdatasets/commit/84c848a424ef688c230fe15350cccff60d406b44

waiting for confirmation from the statsmodels issue

**Comment by josef-pkt** [comment]
it fixes the statsmodels issue, looks good in spot checking some datasets

**Comment by vincentarelbundock** [comment]
thanks a lot, and sorry again for the trouble.

**Comment by josef-pkt** [comment]
Thanks for the quick fix
