### ISSUE TITLE
What Titanic dataset is in this repository?

### ISSUE THREAD

**Issue by clauswilke** [vincentarelbundock/Rdatasets#28]
The Titanic dataset in this repository, available here:
https://github.com/vincentarelbundock/Rdatasets/blob/master/csv/datasets/Titanic.csv
is not the one in the base datasets package. It was added to this repository with this commit: https://github.com/vincentarelbundock/Rdatasets/commit/a4ec76b6cdb9939e594c8d44d718741c63db72bc Any idea where it comes from? It's a more useful dataset, because it has passenger names and ages, but then it's missing crew members.

**Comment by vincentarelbundock** [comment]
Honestly, I'm not sure. It looks like the "datasets" package, but when I
try to load that one, it doesn't look like the one at your link.

There are many Titanic datasets in the full index:
http://vincentarelbundock.github.io/Rdatasets/datasets.html

Perhaps there's a bug in my scraping script that overrides stuff. Not
sure, sorry.

vab

**Comment by clauswilke** [comment]
Ah, looks like the Stat2Data one, which has exactly the same name. This is helpful, thanks.

**Comment by vincentarelbundock** [comment]
Don't know why it ended up in the `datasets` folder though. Might be a bug in the script due to duplicate names. Will leave this issue open, but not sure I'll have time to look into it anytime soon, unfortunately.

**Comment by vincentarelbundock** [comment]
I rewrote the data extraction script. It no longer mixes up datasets with identical names from different packages. Sorry this took so long, and thanks for the report.
