### ISSUE TITLE
Add datasets from heplots and vcdExtra?

### ISSUE THREAD

**Issue by friendly** [vincentarelbundock/Rdatasets#29]
I have two packages with many datasets useful for teaching & research

* [heplots](https://github.com/friendly/heplots) - multivariate linear models, MANOVA, discriminant analysis, ..

* [vcdExtra](https://github.com/friendly/vcdExtra) -- categorical data analysis & visualization

These might be useful to add to Rdatasets -- what would it take?

Also:  take a look at `vcdExtra::datasets()` -- it gives a nice summary of datasets in a package.

**Comment by vincentarelbundock** [comment]
`vcdExtra::datasets` is cool; will definitely be using it.

The two packages should be on the website now. Thanks for the suggestions.
