### ISSUE TITLE
 lmec R Package

### ISSUE THREAD

**Issue by FranciscoAlencar** [vincentarelbundock/Rdatasets#30]
In this package is a database called UTIdata, it refers to censored data. I think the lmec package is not in the RDatasets repository. Could you please check if it is possible to add this package to the RDatasets repository so I can work with the UTIdata database in Julia?

Thank you very much.

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion. The dataset in question is now available at the main website and on github: https://vincentarelbundock.github.io/Rdatasets/
