### ISSUE TITLE
colliding paths

### ISSUE THREAD

**Issue by LFSaw** [vincentarelbundock/Rdatasets#32]
Hello,

thanks for the effort!
When on OSX (a case-insensitive system), I get the following warning; maybe something to look into...

> warning: the following paths have collided (e.g. case-sensitive paths
> on a case-insensitive filesystem) and only one from the same
> colliding group is in the working tree:
>
>  'csv/datasets/CO2.csv'
>  'csv/datasets/co2.csv'
>  'doc/datasets/CO2.html'
>  'doc/datasets/co2.html'
>  'doc/datasets/rst/CO2.rst'
>  'doc/datasets/rst/co2.rst'

**Comment by vincentarelbundock** [comment]
Thanks for the note. Interesting.

I use a case sensitive system, and I'm not exactly sure what problem this poses or what solution is appropriate (I don't want to change URLs at all unless absolutely necessary).

I'll close this issue, but thanks for the info and feel free to comment again if you have things to add.
