### ISSUE TITLE
Additonal datasets from another R package

### ISSUE THREAD

**Issue by kafisatz** [vincentarelbundock/Rdatasets#33]
Would it be possible to add these data sets?

http://cas.uqam.ca/

consider the R code 
```
install.packages("CASdatasets", repos = "http://dutangc.free.fr/pub/RRepos/")
library(CASdatasets)
?CASdatasets 
data(freMTPL2freq)
#data(xy...)
```

**Comment by vincentarelbundock** [comment]
Thanks for the recommendation. Unfortunately, I won't be able to add this one. However, I added it to a list of "omitted packages" in the README, where I explain why it is excluded: 

https://github.com/vincentarelbundock/Rdatasets
