### ISSUE TITLE
Package lmec isn't available anymore

### ISSUE THREAD

**Issue by sjentsch** [vincentarelbundock/Rdatasets#33]
https://cran.r-project.org/web/packages/lmec/

Please remove it from DESCRIPTION.

**Comment by vincentarelbundock** [comment]
Are you the maintainer of lmec?

**Comment by sjentsch** [comment]
No, I am not. But given that the package is archived for about two years now, I am afraid the package is orphaned and there might not be a maintainer anymore.

**Comment by vincentarelbundock** [comment]
Ok. But there might be users who rely on the CSV on RDaatasets, and I don't want to break backward compatibility for them, so I won't remove the data.

But thanks for the note. It's useful infom

**Comment by vincentarelbundock** [comment]
Thanks for the note. The package is removed from the DESCRIPTION, but the datasets are still archived in RDatasets (thought not publicized) to maintain backward compatibility.
