### ISSUE TITLE
Add fpp3 datasets

### ISSUE THREAD

**Issue by ericjb** [vincentarelbundock/Rdatasets#34]
Rdatasets contains the fpp2 datasets (fpp2 = Forecasting Principles and Practice, 2nd edition). I would like to have the fpp3 datasets available on Rdatasets. (fpp3 is the 3rd edition). These datasets are available on CRAN (library(fpp3)). I am willing to help do this and submit a PR if you can point me to some documentation, scripts, etc for guidance. Thanks

**Comment by vincentarelbundock** [comment]
thanks for the suggestion. i updated the website.
