### ISSUE TITLE
Please add the datasets in the R packages tsibble and tsibbledata (used in fpp3)

### ISSUE THREAD

**Issue by ericjb** [vincentarelbundock/Rdatasets#35]
The book fpp3 also refers to datasets in: 
1. the CRAN package **tsibble** (2 datasets) 
2. the CRAN package **tsibbledata** (12 datasets). 

Please add these to Rdatasets. Thanks

p.s. thanks for adding the datasets from fpp3 itself

**Comment by vincentarelbundock** [comment]
This looks like a different data structure. Will scrape.R work OK on those datasets?

**Comment by ericjb** [comment]
I have placed the data in the attached tarball. 
[datasets.tar.gz](https://github.com/vincentarelbundock/Rdatasets/files/15416915/datasets.tar.gz)

**Comment by vincentarelbundock** [comment]
There's a clean_data() function in scrape.R. would the output be useful?

**Comment by ericjb** [comment]
I sent you the csv files in the previous. Can you use those?

**Comment by vincentarelbundock** [comment]
Sure. I can also load them from the package. No time now but might get to it someday

**Comment by ericjb** [comment]
Great. Thanks

**Comment by vincentarelbundock** [comment]
Sorry for the delay. The datasets are now available on RDatasets
