### ISSUE TITLE
add "drc" package datasets

### ISSUE THREAD

**Issue by alejandromerchan** [vincentarelbundock/Rdatasets#36]
Hi,

Thanks for your great work maintaining this resource. Would it be possible to add the "drc" package to the database?
Thanks

**Comment by vincentarelbundock** [comment]
thanks for the suggestion. I'll look into it; should be possible, but it'll take me at least a couple weeks.

**Comment by alejandromerchan** [comment]
Great, thanks for the quick reply.

**Comment by vincentarelbundock** [comment]
added, thanks for the suggestion!
