### ISSUE TITLE
Can't find penguins_raw in datasets.csv

### ISSUE THREAD

**Issue by kojix2** [vincentarelbundock/Rdatasets#8]
Hi @vincentarelbundock and Rdatasets developers

![image](https://user-images.githubusercontent.com/5798442/105722390-f2d1b800-5f68-11eb-8eda-a4987fb10f5a.png)
There is a CSV file called penguins_raw.

![image](https://user-images.githubusercontent.com/5798442/105722471-0b41d280-5f69-11eb-928e-3cc247ee2046.png)
However, this file is not listed in [datasets.csv](https://github.com/vincentarelbundock/Rdatasets/blob/master/datasets.csv#L1007).

Thank you.

**Comment by vincentarelbundock** [comment]
Thanks.

I reported the issue and asked for clarification here: https://github.com/allisonhorst/palmerpenguins/issues/80

**Comment by vincentarelbundock** [comment]
sorry this took so long. I found a workaround and the data are now on the website.
